#!/bin/bash
if [ -d pngs ]; then echo "Directory pngs exists. Exiting.";
else
mkdir pngs
mv main-ez_z0.h5 pngs
echo "Reading metadata..."
NUM_CMD='h5ls pngs/main-ez_z0.h5'
NUM_TEXT=$($NUM_CMD)
NUM_GREP='grep -Po [0-9]+(?=/Inf)'
let NUM=$(echo $NUM_TEXT | $NUM_GREP)-1
echo "File contains frames 0 - $NUM."
echo "Creating images..."
h5topng -t 0:$NUM -R -Zc dkbluered pngs/main-ez_z0.h5
echo "Creating video..."
ffmpeg -framerate 30 -y -i pngs/main-ez_z0.t%0${#NUM}d.png -pix_fmt yuv420p $1.mp4
echo "Cleaning up..."
rm pngs/*.png
mv pngs/main-ez_z0.h5 .
rmdir pngs
echo "Done"
fi
