#!/bin/bash
if [ -d pngs ]; then rm -r pngs; fi
mkdir pngs
echo "Creating images..."
h5topng -t 0:$2 -R -Zc dkbluered main-ez_z0.h5 -o pngs/animation
mv *.t*.png pngs
echo "Creating gif..."
convert pngs/*.png $1.gif
echo "Cleaning up..."
rm pngs/*.png
rmdir pngs
echo "Done"

